apiVersion: v1
kind: ConfigMap
metadata:
  name: env-vars
  namespace: default
data:
  KEYCLOAK_ADMIN_USERNAME: {{ .Values.definitions.keycloak.adminusername }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.definitions.keycloak.adminpassword }}

  DB_USER: {{ .Values.definitions.database.adminusername }}
  DB_PASSWORD: {{ .Values.definitions.database.adminpassword }}
  DB_PORT: '{{ .Values.definitions.database.port }}'
  
  QUIZBUILDER_PORT: '80'
  QUIZBUILDER_DB_SCHEMA: quizbuilder
  QUIZBUILDER_CLIENTID: quizbuilder

  GITEA_REDIRECT_URI: "https://git.{{ .Values.definitions.domain }}/user/oauth2/keycloak/callback"

  GITEA_DB_NAME: {{ .Values.definitions.gitea.database }}
  QUIZBUILDER_DB_NAME: quizbuilder
  KEYCLOAK_DB_NAME: {{ .Values.definitions.keycloak.database }}

  QUIZBUILDER_OAUTH_CLIENT_SECRET: {{ .Values.definitions.quizbuilder.clientsecret }}
  GITEA_OAUTH_CLIENT_SECRET: {{ .Values.definitions.gitea.clientsecret }}

  KEYCLOAK_HOSTNAME: chart-keycloak.default.svc.cluster.local
  DB_HOST: {{ .Values.definitions.database.hostname }}
  QUIZBUILDER_HOSTNAME: quizbuilder.default.svc.cluster.local

  GITEA_INSTANCE_URL: "https://git.{{ .Values.definitions.domain }}"
  GITEA_RUNNER_REGISTRATION_TOKEN: {{ .Values.definitions.gitea.runnerregistration }}
  GITEA_RUNNER_NAME: gitearunner
  #GITEA_RUNNER_LABELS: gitearunnerlabel
